example/mjml-express/Dockerfile, script/run-bench.sh
Signed-off-by: Guillaume Lours <guillaume.lours@docker.com>
=> inline compose up with build, copy package*.json in the same image layer

src/lib.rs, src/mjml/body/mj_body.rs, src/mjml/body/mj_button.rs, src/mjml/body/mj_column.rs, src/mjml/body/mj_divider.rs, src/mjml/body/mj_group.rs, src/mjml/body/mj_hero.rs, src/mjml/body/mj_image.rs, src/mjml/body/mj_navbar/link.rs, src/mjml/body/mj_navbar/main.rs, src/mjml/body/mj_raw.rs, src/mjml/body/mj_section.rs, src/mjml/body/mj_social/element.rs, src/mjml/body/mj_social/main.rs, src/mjml/body/mj_spacer.rs, src/mjml/body/mj_table.rs, src/mjml/body/mj_text.rs, src/mjml/body/mj_wrapper.rs, src/mjml/body/mod.rs, src/mjml/body/raw.rs, src/mjml/head/mj_breakpoint.rs, src/mjml/head/mj_font.rs, src/mjml/head/mj_head.rs, src/mjml/head/mj_preview.rs, src/mjml/head/mj_style.rs, src/mjml/head/mj_title.rs, src/mjml/head/mod.rs, src/mjml/mjml.rs, src/mjml/mod.rs
=> refacto: parse using node reference

src/util/mod.rs, src/util/style.rs, src/util/tag.rs
=> refacto: split html util

Cargo.toml, src/lib.rs, src/mjml/body/mj_accordion/main.rs, src/mjml/body/mj_accordion/text.rs, src/mjml/body/mj_accordion/title.rs, src/mjml/body/mj_body.rs, src/mjml/body/mj_button.rs, src/mjml/body/mj_carousel/image.rs, src/mjml/body/mj_carousel/main.rs, src/mjml/body/mj_column.rs, src/mjml/body/mj_divider.rs, src/mjml/body/mj_group.rs, src/mjml/body/mj_hero.rs, src/mjml/body/mj_image.rs, src/mjml/body/mj_navbar/link.rs, src/mjml/body/mj_navbar/main.rs, src/mjml/body/mj_section.rs, src/mjml/body/mj_social/element.rs, src/mjml/body/mj_social/main.rs, src/mjml/body/mj_spacer.rs, src/mjml/body/mj_table.rs, src/mjml/body/mj_text.rs, src/mjml/body/mj_wrapper.rs
=> refacto: use lazy-static to create default attributes

.circleci/config.yml, Cargo.toml, benches/basic.rs, benches/template.rs, test/template-amario.mjml
=> test: run benchmark of core

src/elements/body/mod.rs, src/elements/body/raw.rs, src/lib.rs, src/parser.rs
=> parser: disable options

src/elements/head/mj_breakpoint.rs, test/mj-breakpoint-default.html, test/mj-breakpoint-default.mjml, test/mj-breakpoint-options.html, test/mj-breakpoint-options.mjml
=> mj-breakpoint: make sure it handles the options

example/mjml-bench/package.json, example/mjml-bench/src/index.js, readme.md
=> doc: update bench section

packages/library/src/elements/body/mj_social/element.rs, packages/library/src/elements/body/mj_social/main.rs, packages/library/src/lib.rs, packages/library/test/mj-social-link.html, packages/library/test/mj-social-link.mjml
Based on https://github.com/jdrouet/mrml/pull/73
=> Mj social noshare

readme.md
=> doc: add code climate badge

code-of-conduct.md, contributing.md, readme.md
=> doc: add contributing and code of conduct

readme.md
=> docs: add more badges to readme

packages/library/src/elements/body/mj_social/element.rs, packages/library/src/elements/body/mj_social/main.rs, packages/library/src/lib.rs, packages/library/src/util/header.rs
From the feature request https://github.com/jdrouet/mrml/issues/83
=> feat(library): add ability to specify origin url for mj-social icons

packages/library/src/parser.rs
=> feat(errors): give position for invalid format parser error

packages/cli/src/main.rs, packages/library/src/elements/body/mj_image/renderer.rs, packages/library/src/elements/mod.rs
=> fix: apply clippy suggestions

packages/library/src/elements/head/mj_attributes/mod.rs, packages/library/src/elements/head/mj_attributes/parser.rs, packages/library/src/elements/head/mj_attributes/renderer.rs, packages/library/src/elements/head/mj_attributes_all/mod.rs, packages/library/src/elements/head/mj_attributes_all/parser.rs, packages/library/src/elements/head/mj_attributes_all/renderer.rs, packages/library/src/elements/head/mj_attributes_class/mod.rs, packages/library/src/elements/head/mj_attributes_class/parser.rs, packages/library/src/elements/head/mj_attributes_class/renderer.rs, packages/library/src/elements/head/mj_attributes_element/mod.rs, packages/library/src/elements/head/mj_attributes_element/parser.rs, packages/library/src/elements/head/mj_attributes_element/renderer.rs, packages/library/src/elements/head/mod.rs
=> refactor(library): split mj-attributes

.gitlab-ci.yml
=> ci: publish bench to codebench

packages/library/src/elements/body/mj_carousel/renderer.rs, packages/library/src/elements/body/mj_column/renderer.rs, packages/library/src/elements/body/mj_navbar/renderer.rs, packages/library/src/elements/body/mj_navbar_link/renderer.rs, packages/library/src/elements/body/mj_section/renderer.rs, packages/library/src/elements/body/mj_wrapper/renderer.rs
=> fix(library): satisfy clippy proposal

packages/library/src/elements/body/generic.rs, packages/library/src/elements/body/mj_navbar_link/parser.rs, packages/library/src/elements/body/raw/parser.rs, packages/library/src/elements/head/mj_attributes/children.rs, packages/library/src/elements/mod.rs, packages/library/src/lib.rs, packages/library/src/util/attributes.rs, packages/library/src/util/context.rs, packages/library/src/util/header.rs, packages/library/src/util/size.rs, packages/library/src/util/spacing.rs, packages/library/src/util/tag.rs
=> refacto(library): remove usuned code

packages/library/src/elements/body/mj_accordion_title/mod.rs, packages/library/src/elements/body/mj_carousel/renderer.rs, packages/library/src/elements/body/mj_navbar/renderer.rs, packages/library/src/elements/head/mj_head/renderer.rs, packages/library/src/util/attributes.rs
=> refacto(library): use default string

packages/library/src/util/header.rs, packages/library/src/util/tag.rs
=> refacto(library): use iterators

packages/library/src/elements/mjml/mod.rs, packages/library/src/elements/mjml/parser.rs, packages/library/src/elements/mjml/renderer.rs
=> refacto(library): split mjml element

.gitlab-ci.yml
=> build(ci): use clippy image

.gitlab-ci.yml, packages/mrml-core/src/comment/render.rs, packages/mrml-core/src/mj_breakpoint/parse.rs, packages/mrml-core/src/mj_carousel/parse.rs, packages/mrml-core/src/mj_carousel/print.rs, packages/mrml-core/src/mj_font/json.rs, packages/mrml-core/src/mj_font/mod.rs, packages/mrml-core/src/mj_font/parse.rs, packages/mrml-core/src/mj_head/parse.rs, packages/mrml-core/src/mj_head/print.rs, packages/mrml-core/src/mj_preview/parse.rs, packages/mrml-core/src/mj_title/parse.rs
=> increase code coverage

readme.md
=> doc: mention mrml-cli

packages/mrml-wasm/Cargo.toml, packages/mrml-wasm/readme.md, packages/mrml-wasm/src/lib.rs, packages/mrml-wasm/tests/wasm.rs
=> feat(wasm): add toJson, toMjml and validate

packages/mrml-core/src/lib.rs, packages/mrml-core/src/mj_head/children.rs, packages/mrml-core/src/mj_head/render.rs, packages/mrml-core/src/mj_style/json.rs, packages/mrml-core/src/mj_style/mod.rs, packages/mrml-core/src/mj_style/parse.rs, packages/mrml-core/src/mj_style/print.rs
=> feat(mj-style): implement missing mj-style component

packages/mrml-core/src/mj_breakpoint/json.rs, packages/mrml-core/src/mj_breakpoint/mod.rs, packages/mrml-core/src/mj_breakpoint/parse.rs, packages/mrml-core/src/mj_breakpoint/print.rs, packages/mrml-core/src/mj_head/json.rs, packages/mrml-core/src/mj_head/print.rs
=> fix(core): replace value attribute by width

packages/mrml-core/src/lib.rs, packages/mrml-core/src/mj_body/children.rs, packages/mrml-core/src/mj_table/json.rs, packages/mrml-core/src/mj_table/mod.rs, packages/mrml-core/src/mj_table/parse.rs, packages/mrml-core/src/mj_table/print.rs, packages/mrml-core/src/mj_table/render.rs
Fixes https://github.com/jdrouet/mrml/issues/143
=> feat(core): add missing mj-table element

.github/semantic.yml
=> chore(ci): add semantics to lint commits

packages/mrml-core/src/mj_head/render.rs, resources/compare/success/mj-style.html
=> fix(mrml-core): make sure mj-style components output style elements

packages/mrml-core/src/helper/tag.rs, packages/mrml-core/src/helper/test.rs, packages/mrml-core/src/mj_accordion_text/render.rs, packages/mrml-core/src/mj_accordion_title/render.rs, packages/mrml-core/src/mj_body/render.rs, packages/mrml-core/src/mj_button/render.rs, packages/mrml-core/src/mj_carousel/render.rs, packages/mrml-core/src/mj_carousel_image/render.rs, packages/mrml-core/src/mj_divider/render.rs, packages/mrml-core/src/mj_group/render.rs, packages/mrml-core/src/mj_section/render.rs, packages/mrml-core/src/mj_social/render.rs, packages/mrml-core/src/mj_social_element/render.rs, packages/mrml-core/src/mj_table/render.rs, packages/mrml-core/src/mj_text/render.rs, packages/mrml-core/src/mj_wrapper/render.rs
Fix for https://github.com/jdrouet/mrml/issues/154
=> fix(mrml-core): keep style content order

.gitlab-ci.yml
=> chore(ci): add hyperfine test

packages/mrml-core/src/mj_social/render.rs
=> fix(mrml-core): update following clippy error

.gitlab-ci.yml, packages/mrml-core/src/mj_column/render.rs, packages/mrml-core/src/mj_group/render.rs, packages/mrml-core/src/mj_head/render.rs, packages/mrml-core/src/mj_section/render.rs, packages/mrml-core/src/mjml/parse.rs
=> fix(mrml-core): handle owa attribute on mjml tag

Cargo.lock, packages/mrml-core/Cargo.toml, packages/mrml-core/src/helper/condition.rs, packages/mrml-core/src/helper/test.rs, packages/mrml-core/src/mj_body/render.rs, packages/mrml-core/src/mj_head/render.rs, packages/mrml-core/src/mj_section/mod.rs, packages/mrml-core/src/mj_section/render.rs, packages/mrml-core/src/mj_text/render.rs, packages/mrml-core/src/mj_wrapper/render.rs, packages/mrml-core/src/mjml/render.rs, resources/compare/success/mj-raw-head.html, resources/compare/success/mj-raw.html, resources/template/air-astana.html, resources/template/air-astana.mjml
=> fix(mrml-core): simplify mj-wrapper renderer

packages/mrml-core/src/mj_wrapper/parse.rs, packages/mrml-core/src/node/parse.rs, packages/mrml-core/src/prelude/parse.rs
=> feat(mrml-core): handle self closing element

packages/mrml-core/resources/compare/success/comment.html, packages/mrml-core/resources/compare/success/comment.mjml, packages/mrml-core/resources/compare/success/mj-carousel-align-border-radius-class.html, packages/mrml-core/resources/compare/success/mj-carousel-icon.html, packages/mrml-core/resources/compare/success/mj-carousel-tb.html, packages/mrml-core/resources/compare/success/mj-carousel-thumbnails.html, packages/mrml-core/resources/compare/success/mj-navbar-ico.html, packages/mrml-core/resources/compare/success/mj-navbar.html, packages/mrml-core/resources/template/amario.html, packages/mrml-core/src/mj_section/render.rs, scripts/package-lock.json
=> fix(mrml-core): update template and fix mj-section with comment

packages/mrml-core/src/mj_head/parse.rs
Fixes https://github.com/jdrouet/mrml/issues/373
=> fix(mrml-core): add missing comment parser for mj-head

packages/mrml-core/src/mj_head/render.rs, packages/mrml-core/tests/multiple-mj-font.rs
=> fix(mrml-core): ensure fonts are rendered once

packages/mrml-core/src/mj_accordion/render.rs, packages/mrml-core/src/prelude/render.rs
=> refactor(mrml-core): styles are stored in Set<Cow<'static, str>>

packages/mrml-core/src/mj_attributes/mod.rs, packages/mrml-core/src/mj_attributes_class/mod.rs, packages/mrml-core/src/mj_attributes_element/mod.rs
=> refactor(mrml-core): make MjAttributes children public

packages/mrml-core/src/prelude/parser/mod.rs, packages/mrml-core/tests/issue-439.rs
=> fix: keep whitespaces when need

Cargo.lock, packages/mrml-wasm/Cargo.toml, packages/mrml-wasm/src/lib.rs
Remove unmaintained dependency https://github.com/jdrouet/mrml/security/dependabot/117
=> fix(mrml-wasm): remove wee_alloc dependency
